name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  SCRIPT_ID: ${{ secrets.SCRIPT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: create .clasp.json
        run: |
          echo "{\"scriptId\":\"${{ env.SCRIPT_ID }}", \"rootDir\": \"$(pwd)\" }"" > .clasp.json

      - name: deploy
        run: npm run deploy
