name: Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: deploy
        run: npm run deploy
